### PR TITLE
Pretty print unified diff with 5 line before/after window

### LINKED ISSUE #9: Don't print the whole file when there's a diff
For our OpenAPI specs, a failed assert_contents prints a few thousand lines.

### PR DESCRIPTION
**Pull request by david-crespo**
Closes #9

Tried and failed to make it work with `difference` and [`pretty_assertions`](https://docs.rs/pretty_assertions/0.6.1/pretty_assertions/). Found success with [Similar](https://insta.rs/similar/). Very clean.

This is already a net improvement as-is, but some possible improvements:

- use color
- increase window size to 10 or something
- tests could assert what gets printed to stdout instead of only checking for the panic

### one line difference

Screen Shot 2022-03-18 at 4 37 22 PM
 
### all lines difference

Screen Shot 2022-03-18 at 4 37 33 PM

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -69,9 +69,9 @@ pub fn assert_contents<P: AsRef<Path>>(path: P, actual: &str) {
         let expected = dos2unix(&expected_s);
 
         if expected != actual {
-            let changeset =
-                Changeset::new(expected.as_ref(), actual.as_ref(), "\n");
-            println!("{}", changeset);
+            let diff =
+                unified_diff(Algorithm::Myers, &expected, &actual, 5, None);
```
Comment (david-crespo) [inline src/lib.rs:73]: Myers is the default algorithm in git, so that seems fine. 5 is the number of lines before and after. `None` could be replaced with a header representing the two file names, not sure if we care.

Comment (ahl) [reply src/lib.rs]: Yeah there's only one file and it should be clear from context so agreed that it's not useful to add a header
